name: Build RandomWars JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Встановлюємо JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Встановлюємо Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # 4. Збираємо проект у корені
      - name: Build with Gradle
        run: gradle clean build

      # 5. Завантажуємо JAR як артефакт
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: RandomWars-jar
          path: build/libs/*.jar
